#spring.application.name=chamados

# ===============================
# DATABASE
# ===============================
#spring.datasource.url=seubanco
#spring.datasource.username=root
#spring.datasource.password=sua senha

# ===============================
# JPA / HIBERNATE
# ===============================
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================
#server.port=8080